# Generated by Django 5.2.3 on 2025-07-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
